// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	CompanyName   string             `json:"company_name"`
	JobTitle      string             `json:"job_title"`
	JobUrl        pgtype.Text        `json:"job_url"`
	AppliedAt     pgtype.Timestamptz `json:"applied_at"`
	Status        string             `json:"status"`
	EmailThreadID pgtype.Text        `json:"email_thread_id"`
	Notes         pgtype.Text        `json:"notes"`
	Tags          []string           `json:"tags"`
	ResumeVersion pgtype.Text        `json:"resume_version"`
	StatusHistory []byte             `json:"status_history"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
