// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteApplication(ctx context.Context, id pgtype.UUID) error
	GetApplicationByID(ctx context.Context, id pgtype.UUID) (Application, error)
	GetApplicationsByUser(ctx context.Context, userID pgtype.UUID) ([]Application, error)
	InsertApplication(ctx context.Context, arg InsertApplicationParams) (Application, error)
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
	UpdateApplicationThreadID(ctx context.Context, arg UpdateApplicationThreadIDParams) error
}

var _ Querier = (*Queries)(nil)
